version: 2
updates:
  - package-ecosystem: "gradle"
    ignore:
      - dependency-name: "io.github.libxposed:api"
        versions: [">=102"]
      - dependency-name: "io.github.libxposed:service"
        versions: [">=102"]
    commit-message:
      prefix: "ci(deps)"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
